package com.mycompany.library_manaement_system.View;

import com.mycompany.library_manaement_system.Controller.BookController;
import com.mycompany.library_manaement_system.Controller.TransactionController;
import com.mycompany.library_manaement_system.Controller.UserController;
import com.mycompany.library_manaement_system.data.Models.Book;
import com.mycompany.library_manaement_system.data.Models.Transaction;
import com.mycompany.library_manaement_system.data.Models.User;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AdminForm extends javax.swing.JFrame {

    private UserController userController;
    private BookController bookController;
    private TransactionController transactionController;
    private DefaultTableModel userTableModel;
    private DefaultTableModel bookTableModel;

    public AdminForm() {
        userController = new UserController();
        bookController = new BookController();
        transactionController = new TransactionController(bookController);

        initComponents();
        initCustomComponents(); // For table models and initial data loading
        setTitle("Admin Dashboard");
        setLocationRelativeTo(null);
    }

    private void initCustomComponents() {
        // User Table Model
        String[] userColumns = { "ID", "Username", "Password", "Type", "Email" };
        userTableModel = new DefaultTableModel(userColumns, 0);
        userTable.setModel(userTableModel);
        loadUsers();

        // Book Table Model
        String[] bookColumns = { "ID", "Title", "Author", "Genre", "Year", "Status" };
        bookTableModel = new DefaultTableModel(bookColumns, 0);
        bookTable.setModel(bookTableModel);
        loadBooks();

        // Transaction Table loading
        loadTransactions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        logoutButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        userPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        userPassField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userEmailField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        userTypeCombo = new javax.swing.JComboBox<>();
        addUserButton = new javax.swing.JButton();
        updateUserButton = new javax.swing.JButton();
        deleteUserButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        bookPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bookTitleField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bookAuthorField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bookGenreField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bookYearField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bookStatusCombo = new javax.swing.JComboBox<>();
        addBookButton = new javax.swing.JButton();
        updateBookButton = new javax.swing.JButton();
        deleteBookButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        transactionPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        transTable = new javax.swing.JTable();
        refreshTransButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        jLabel3.setText("Email:");

        jLabel4.setText("Type:");

        userTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(
                com.mycompany.library_manaement_system.data.Models.User.UserType.values()));

        addUserButton.setText("Add User");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        updateUserButton.setText("Update Selected");
        updateUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserButtonActionPerformed(evt);
            }
        });

        deleteUserButton.setText("Delete Selected");
        deleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(userNameField)
                                                        .addComponent(userPassField)
                                                        .addComponent(userEmailField)
                                                        .addComponent(userTypeCombo, 0,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(addUserButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(updateUserButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(deleteUserButton)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(userPassField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(userEmailField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(userTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addUserButton)
                                        .addComponent(updateUserButton)
                                        .addComponent(deleteUserButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(userTable);

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
                userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(userPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 976,
                                                Short.MAX_VALUE))
                                .addContainerGap()));
        userPanelLayout.setVerticalGroup(
                userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(userPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                                .addContainerGap()));

        jTabbedPane1.addTab("Manage Users", userPanel);

        jLabel5.setText("Title:");

        jLabel6.setText("Author:");

        jLabel7.setText("Genre:");

        jLabel8.setText("Year:");

        jLabel9.setText("Status:");

        bookStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(
                com.mycompany.library_manaement_system.data.Models.Book.BookStatus.values()));

        addBookButton.setText("Add Book");
        addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonActionPerformed(evt);
            }
        });

        updateBookButton.setText("Update Selected");
        updateBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBookButtonActionPerformed(evt);
            }
        });

        deleteBookButton.setText("Delete Selected");
        deleteBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel9))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(bookTitleField)
                                                        .addComponent(bookAuthorField)
                                                        .addComponent(bookGenreField)
                                                        .addComponent(bookYearField)
                                                        .addComponent(bookStatusCombo, 0,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(addBookButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(updateBookButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(deleteBookButton)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(bookTitleField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(bookAuthorField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(bookGenreField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(bookYearField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(bookStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addBookButton)
                                        .addComponent(updateBookButton)
                                        .addComponent(deleteBookButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane2.setViewportView(bookTable);

        javax.swing.GroupLayout bookPanelLayout = new javax.swing.GroupLayout(bookPanel);
        bookPanel.setLayout(bookPanelLayout);
        bookPanelLayout.setHorizontalGroup(
                bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bookPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 976,
                                                Short.MAX_VALUE))
                                .addContainerGap()));
        bookPanelLayout.setVerticalGroup(
                bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bookPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                .addContainerGap()));

        jTabbedPane1.addTab("Manage Books", bookPanel);

        transTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane3.setViewportView(transTable);

        refreshTransButton.setText("Refresh");
        refreshTransButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTransButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transactionPanelLayout = new javax.swing.GroupLayout(transactionPanel);
        transactionPanel.setLayout(transactionPanelLayout);
        transactionPanelLayout.setHorizontalGroup(
                transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(transactionPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(transactionPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 976,
                                                Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                transactionPanelLayout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(refreshTransButton)))
                                .addContainerGap()));
        transactionPanelLayout.setVerticalGroup(
                transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(transactionPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refreshTransButton)
                                .addContainerGap()));

        jTabbedPane1.addTab("View Transactions", transactionPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logoutButton)
                                .addContainerGap())
                        .addComponent(jTabbedPane1));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(logoutButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTabbedPane1)
                                .addContainerGap()));

        pack();
    }// </editor-fold>

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {
        new RegisterForm().setVisible(true);
        dispose();
    }

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String name = userNameField.getText();
        String pass = userPassField.getText();
        String email = userEmailField.getText();
        User.UserType type = (User.UserType) userTypeCombo.getSelectedItem();

        if (name.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username and Password required.");
            return;
        }

        User newUser = new User(0, name, pass, email, type); // ID generated by controller
        if (userController.addUser(newUser)) {
            loadUsers();
            JOptionPane.showMessageDialog(this, "User added.");
        } else {
            JOptionPane.showMessageDialog(this, "User already exists.");
        }
    }

    private void updateUserButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int row = userTable.getSelectedRow();
        if (row == -1)
            return;
        int id = (int) userTableModel.getValueAt(row, 0);

        String name = userNameField.getText();
        String pass = userPassField.getText();
        String email = userEmailField.getText();
        User.UserType type = (User.UserType) userTypeCombo.getSelectedItem();

        if (userController.updateUser(id, name, pass, email, type)) {
            loadUsers();
            JOptionPane.showMessageDialog(this, "User updated.");
        }
    }

    private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int row = userTable.getSelectedRow();
        if (row == -1)
            return;
        int id = (int) userTableModel.getValueAt(row, 0);

        if (userController.deleteUser(id)) {
            loadUsers();
            JOptionPane.showMessageDialog(this, "User deleted.");
        }
    }

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String title = bookTitleField.getText();
            String author = bookAuthorField.getText();
            String genre = bookGenreField.getText();
            int year = Integer.parseInt(bookYearField.getText());
            Book.BookStatus status = (Book.BookStatus) bookStatusCombo.getSelectedItem();

            Book newBook = new Book(0, title, author, genre, year, status);
            bookController.addBook(newBook);
            loadBooks();
            JOptionPane.showMessageDialog(this, "Book added.");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Year must be a number.");
        }
    }

    private void updateBookButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int row = bookTable.getSelectedRow();
        if (row == -1)
            return;
        int id = (int) bookTableModel.getValueAt(row, 0);

        try {
            String title = bookTitleField.getText();
            String author = bookAuthorField.getText();
            String genre = bookGenreField.getText();
            int year = Integer.parseInt(bookYearField.getText());
            Book.BookStatus status = (Book.BookStatus) bookStatusCombo.getSelectedItem();

            if (bookController.updateBook(id, title, author, genre, year, status)) {
                loadBooks();
                JOptionPane.showMessageDialog(this, "Book updated.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Year must be a number.");
        }
    }

    private void deleteBookButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int row = bookTable.getSelectedRow();
        if (row == -1)
            return;
        int id = (int) bookTableModel.getValueAt(row, 0);

        if (bookController.deleteBook(id)) {
            loadBooks();
            JOptionPane.showMessageDialog(this, "Book deleted.");
        }
    }

    private void refreshTransButtonActionPerformed(java.awt.event.ActionEvent evt) {
        loadTransactions();
    }

    private void loadUsers() {
        userTableModel.setRowCount(0);
        for (User u : userController.getAllUsers()) {
            userTableModel
                    .addRow(new Object[] { u.getId(), u.getUsername(), u.getPassword(), u.getType(), u.getGmail() });
        }
    }

    private void loadBooks() {
        bookTableModel.setRowCount(0);
        for (Book b : bookController.getAllBooks()) {
            bookTableModel.addRow(
                    new Object[] { b.getId(), b.getTitle(), b.getAuthor(), b.getGenre(), b.getYear(), b.getStatus() });
        }
    }

    private void loadTransactions() {
        String[] columns = { "ID", "User ID", "Book ID", "Type", "Date" };
        DefaultTableModel transModel = new DefaultTableModel(columns, 0);

        // Re-read from file
        transactionController.readTransactionsFromFile();
        for (Transaction t : transactionController.getAllTransactions()) {
            transModel.addRow(new Object[] { t.getId(), t.getUserId(), t.getBookId(), t.getType(), t.getDate() });
        }
        transTable.setModel(transModel);
    }

    
    private javax.swing.JButton addBookButton;
    private javax.swing.JButton addUserButton;
    private javax.swing.JTextField bookAuthorField;
    private javax.swing.JTextField bookGenreField;
    private javax.swing.JPanel bookPanel;
    private javax.swing.JComboBox<Book.BookStatus> bookStatusCombo;
    private javax.swing.JTable bookTable;
    private javax.swing.JTextField bookTitleField;
    private javax.swing.JTextField bookYearField;
    private javax.swing.JButton deleteBookButton;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton refreshTransButton;
    private javax.swing.JTable transTable;
    private javax.swing.JPanel transactionPanel;
    private javax.swing.JButton updateBookButton;
    private javax.swing.JButton updateUserButton;
    private javax.swing.JTextField userEmailField;
    private javax.swing.JTextField userNameField;
    private javax.swing.JPanel userPanel;
    private javax.swing.JTextField userPassField;
    private javax.swing.JTable userTable;
    private javax.swing.JComboBox<User.UserType> userTypeCombo;
    
}
