package com.mycompany.library_manaement_system.View;

import com.mycompany.library_manaement_system.Controller.BookController;
import com.mycompany.library_manaement_system.Controller.TransactionController;
import com.mycompany.library_manaement_system.Controller.UserController;
import com.mycompany.library_manaement_system.data.Models.Book;
import com.mycompany.library_manaement_system.data.Models.Transaction;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class LibrarianForm extends javax.swing.JFrame {

    private BookController bookController;
    private TransactionController transactionController;
    // userController is initialized but not heavily used here, keeping for
    // consistency
    private UserController userController;
    private DefaultTableModel reservationTableModel;

    public LibrarianForm() {
        bookController = new BookController();
        transactionController = new TransactionController(bookController);
        userController = new UserController();

        initComponents();
        loadReservations();
        setTitle("Librarian Dashboard");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        logoutButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        circulationPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userIdField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bookIdField = new javax.swing.JTextField();
        checkoutButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        reservationPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservationTable = new javax.swing.JTable();
        approveButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("User ID:");

        jLabel2.setText("Book ID:");

        checkoutButton.setText("Check Out Book");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });

        returnButton.setText("Return Book");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(userIdField)
                                                        .addComponent(bookIdField)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(checkoutButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(returnButton)
                                                .addGap(0, 755, Short.MAX_VALUE)))
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(bookIdField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(checkoutButton)
                                        .addComponent(returnButton))
                                .addContainerGap(420, Short.MAX_VALUE)));

        javax.swing.GroupLayout circulationPanelLayout = new javax.swing.GroupLayout(circulationPanel);
        circulationPanel.setLayout(circulationPanelLayout);
        circulationPanelLayout.setHorizontalGroup(
                circulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(circulationPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        circulationPanelLayout.setVerticalGroup(
                circulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(circulationPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        jTabbedPane1.addTab("Circulation", circulationPanel);

        reservationTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(reservationTable);

        approveButton.setText("Approve Selected Reservation");
        approveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveButtonActionPerformed(evt);
            }
        });

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reservationPanelLayout = new javax.swing.GroupLayout(reservationPanel);
        reservationPanel.setLayout(reservationPanelLayout);
        reservationPanelLayout.setHorizontalGroup(
                reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(reservationPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(reservationPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988,
                                                Short.MAX_VALUE)
                                        .addGroup(reservationPanelLayout.createSequentialGroup()
                                                .addComponent(approveButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(refreshButton)))
                                .addContainerGap()));
        reservationPanelLayout.setVerticalGroup(
                reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(reservationPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(reservationPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(approveButton)
                                        .addComponent(refreshButton))
                                .addContainerGap(15, Short.MAX_VALUE)));

        jTabbedPane1.addTab("Reservations", reservationPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logoutButton)
                                .addContainerGap())
                        .addComponent(jTabbedPane1));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(logoutButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTabbedPane1)
                                .addContainerGap()));

        pack();
    }// </editor-fold>

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {
        new RegisterForm().setVisible(true);
        dispose();
    }

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int userId = Integer.parseInt(userIdField.getText());
            int bookId = Integer.parseInt(bookIdField.getText());

            if (transactionController.checkoutBook(userId, bookId)) {
                JOptionPane.showMessageDialog(this, "Book Checked Out Successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Checkout Failed! Book may not be available or user invalid.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric IDs.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int userId = Integer.parseInt(userIdField.getText());
            int bookId = Integer.parseInt(bookIdField.getText());

            if (transactionController.returnBook(userId, bookId)) {
                JOptionPane.showMessageDialog(this, "Book Returned Successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Return Failed! No active transaction found.", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric IDs.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void approveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = reservationTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a reservation to approve.");
            return;
        }

        int bookId = (int) reservationTableModel.getValueAt(selectedRow, 0);
        int userId = (int) reservationTableModel.getValueAt(selectedRow, 2); // Assuming User ID is in column 2

        // Logic to approve: Find the book, set it to Available (essentially cancelling
        // reservation so they can check out)
        // OR better: Execute a checkout for them.
        // For simplicity based on previous requirements: Librarian validates it.
        // Let's assume approval means converting Reservation to Checkout or just
        // notifying.
        // But TransactionController doesn't have an explicit 'approveReservation'.
        // Let's implement it as checkout.

        if (transactionController.checkoutBook(userId, bookId)) {
            JOptionPane.showMessageDialog(this, "Reservation Approved & Book Checked Out.");
            loadReservations();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to approve reservation.");
        }
    }

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {
        loadReservations();
    }

    private void loadReservations() {
        String[] columns = { "Book ID", "Title", "User ID", "Date" };
        reservationTableModel = new DefaultTableModel(columns, 0);

        for (Transaction t : transactionController.getAllTransactions()) {
            if (t.getType() == Transaction.TransactionType.Reserve) {
                // Find book title for display
                Book b = bookController.getAllBooks().stream().filter(bk -> bk.getId() == t.getBookId()).findFirst()
                        .orElse(null);
                String title = (b != null) ? b.getTitle() : "Unknown";
                reservationTableModel.addRow(new Object[] { t.getBookId(), title, t.getUserId(), t.getDate() });
            }
        }
        reservationTable.setModel(reservationTableModel);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton approveButton;
    private javax.swing.JTextField bookIdField;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JPanel circulationPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JPanel reservationPanel;
    private javax.swing.JTable reservationTable;
    private javax.swing.JButton returnButton;
    private javax.swing.JTextField userIdField;
    // End of variables declaration
}
